### ISSUE TITLE
Why is this so diverged from Nixpkgs?

### ISSUE THREAD

**Issue by 0xABAB** [ip1981/nixsap#21]
And, do you have plans to ever do PRs for it in Nixpkgs? 

Would you even want to see parts of it in Nixpkgs? 

Do you think it's too much hassle to get services in Nixpkgs? 

Do you believe to have deep disagreement with design decisions in Nixpkgs?

**Comment by ip1981** [comment]
First of all, it's not diverged. It's an independent set of NixOS modules :)
One can try `nixsap.apps.postgresql.foo` or `services.postgresql` at the same time.
That's what I love about NixOS modules.

Thus there is little sense in expecting it to be merged in Nixpkgs, because it is ... parallel. This thing is a kind of experiment, I don't hesitate to break things and I do that :) This is targeting _unattended_ server environments and there are some issues with Nixpkgs that I don't like, that's true. Most services are poorly designed (they could be more declarative) or/and are legacy and should maintain backward compatibility.

Also I don't like some things about packages (not services) in Nixpkgs. But that's another story.

Anyway, again, Nixsap is built on top of Nixpkgs. One can use it or vanila Nixpkgs, override packages overridden by Nixsap, or use Nixsap option sets to get as flexible specifications as possible.

I will create a demo project eventually.

**Comment by 0xABAB** [comment]
@ip1981 Thanks for your explanation.
